package com.javase.chapter13;

public class Test02 {
	//抛出异常后在调用该方法的代码处处理
		public void test021() throws Exception{
			int i  = 3;
			int j = 0;
			if(j==0){
				throw new Exception();
			}else{
				
			}
		}
}
